language: php
php:
 - "5.3"
 - "5.4"
 - "5.5"

before_install:
 - composer self-update
 - composer install --dev
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
 - phpunit -c tests --coverage-clover ./coverage/clover.xml
 - output=$(php php-cs-fixer.phar fix -v --dry-run --level=all ./src); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
 - output=$(php php-cs-fixer.phar fix -v --dry-run --level=all ./tests); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

after_script:
 - ./vendor/bin/coveralls -v
