<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BaconStringUtils\UniDecoderTest' => __DIR__ . '/tests/BaconStringUtils/UniDecoderTest.php',
    'BaconStringUtils\SlugifierTest'  => __DIR__ . '/tests/BaconStringUtils/SlugifierTest.php',
    'BaconStringUtils\Slugifier'      => __DIR__ . '/src/BaconStringUtils/Slugifier.php',
    'BaconStringUtils\UniDecoder'     => __DIR__ . '/src/BaconStringUtils/UniDecoder.php',
    'BaconStringUtils\Module'         => __DIR__ . '/Module.php',
);